
CREATE TABLE export_lancetAll
( 
 
 Tender_ID INT NOT NULL,
 PublDt datetime NULL,
 LancetUPDATEPartition datetime NOT NULL,
 TenderSYSDATE  datetime NOT NULL,
 NotifNr  varchar(50) NULL,
 StatusT_ID  INT NOT NULL, 
 StatusT_name  varchar(8000) NULL,
 FormT_ID  INT NOT NULL, 
 FormT_name  varchar(50) NULL,
 T_RegID  INT NOT NULL, 
 RegNm  varchar(50) NULL,
 Org_CustNm  varchar(500) NULL,
 INN varchar(24) NULL,
 KPP varchar(24) NULL,
 OGRN varchar(25) NULL,
 Org_SubCustNm  varchar(500) NULL,
 Org_ProviderNm  varchar(500) NULL,
 ClaimReglament  varchar(3000) NULL,
 ClaimDtBeg  datetime NULL,
 ClaimDtEnd  datetime NULL,
 TendDt  datetime NULL,
 Budget  char(1) NULL,
 Budgets_Name  varchar(8000) NULL,
 TenderDocReglament  varchar(250) NULL,
 TendNm  varchar(500) NULL,
 TenderPrice  decimal(18,2) NULL,
 TenderLot  INT NULL, 
 SMP  varchar(3) NOT NULL,
 PaymentReglament  varchar(3000) NULL,
 LotNr  varchar(50) NULL,
 LotNm  varchar(500) NULL,
 LotType  varchar(50) NULL,
 pozicion  varchar(50) NULL,
 OKEI_Name  varchar(10) NULL,
 Lot_ID_tmp  INT NULL, 
 LotPriceStart  decimal(18,2) NULL,
 LotPriceMax  decimal(18,2) NULL,
 LotPriceDiff  decimal(18,2) NULL,
 LotPos  INT NULL, 
 LotSpecPos  INT NULL, 
 InnR  varchar(900) NULL,
 TradeNmR  varchar(254) NULL,
 ProdNm  varchar(500) NULL,
 Form  varchar(1000) NULL,
 LotSpecPrice  decimal(18,2) NULL,
 LotSpecNum  INT NULL, 
 LotSpecValue  decimal(18,2) NULL,
 Unit_ID  INT NULL, 
 UnitsName  varchar(40) NULL,
 LotRegion  varchar(50) NULL,
 ConsigneeNm  varchar(500) NULL,
 ConsigneeInfo  varchar(250) NULL,
 PlanT_ID  INT NULL, 
 PlanName  varchar(8000) NULL,
 PlanTYear  INT NULL, 
 PlanTVal  varchar(3000) NULL,
 WinnerOrg  varchar(500) NULL,
 WinnerInfo  varchar(500) NULL,
 SupplyReglament  varchar(500) NULL,
 LotPriceOther  decimal(18,2) NULL,
 SrcInf  varchar(500) NULL,
 ClaimObesp  decimal(18,2) NULL,
 ContrObesp  decimal(18,2) NULL,
 LS_TradeNm_ID  INT NULL, 
 LS_MNN_ID  INT NULL, 
 Reg_ID  INT NOT NULL, 
 Lot_ID  INT NULL, 
 Lot_Reg_ID  INT NULL, 
 LotSpec_ID  INT NULL, 
 OrgType  varchar(100) NULL,
 TenderUPDDATE  datetime NULL,
 FO_ID  INT NULL,
 FO_Nm  varchar(150) NULL,
 Cust_ID  INT NULL,
 consID  INT NULL,
 Winner_ID  INT NULL,
 Id_DrugFmNmR  INT NULL,
 Id_FormName  INT NULL,
 DrugFmNmR  nvarchar(100) NULL,
 FormName  nvarchar(254) NULL,
 MunLevel  varchar(100) NULL,
 Org_ID  INT NULL,
 Pr_Name  varchar(1000) NULL,
 Pr_Price  money NULL,
 Pr_Quantity  money NULL,
 Pr_Sum  money NULL,
 NumberContract  varchar(257) NULL,
 SignDate  date NULL,
 Su_OrganizationName  nvarchar(4000) NULL,
 Su_Inn  nvarchar(54) NULL,
 Su_Kpp  nvarchar(54) NULL,
 IDLOTSPEC  INT NULL,
 ShortName  varchar(10) NULL,
 Lgotaname  varchar(50) NULL,
 Tender_ID_tmp  INT NULL,
 CntWin  INT NULL,
 lotTypeID  INT NULL,
 Proizvoditel  varchar(100) NULL,
 lssysdate  datetime NULL,
 ProductIdNx  INT NULL,
 OrgNmShot  varchar(255) NULL,
 TndChangeType  varchar(250) NULL,
 TndChangeT_id  INT NULL,
 TndCancelType  varchar(500) NULL,
 TndCancelT_id  INT NULL,
 IsTheEnd  INT NULL,
 IsTheEndID  INT NULL,
 CnPrice  decimal(18,2) NULL,
 Cnhref  varchar(1024) NULL,
 CntLS  INT NULL,
 isMultiple  varchar(3) NOT NULL,
 ProdTypeDescr  varchar(250) NULL,
 ProdType_id  char(1) NULL,
 ContractsATC  varchar(3) NOT NULL,
 ContractsTheEnd  varchar(3) NOT NULL,
 ProductsProducer  varchar(255) NULL,
 TenderSrcPlan  varchar(200) NULL,
 ClaimProcDtEnd  datetime NULL,
 ContractsRegNum  varchar(257) NULL,
 LotSpecNumPack  INT NULL,
 LotSpecPricePack  decimal(18,2) NULL,
 ConCustNM  varchar(2000) NULL,
 cust_regNum  varchar(11) NULL,
 ContractStageCode  varchar(2) NULL,
 ContractStageNM  varchar(50) NULL,
 HandChek  varchar(3) NOT NULL,
 comment  INT NULL,
 ContractIdNx  INT NULL,
 ConDrugFmNmR  nvarchar(100) NULL,
 ConFormName  nvarchar(254) NULL,
 TradeNmRContr  nvarchar(254) NULL,
 InnrContr  varchar(900) NULL,
 ContractsNoTRADE  varchar(3) NOT NULL,
 INNCONCUST  varchar(16) NULL,
 NumberCustinn  varchar(11) NULL,
 LotSpecUPDDATE  datetime NULL,
 Addr1   varchar(250) NULL,
 InnE  varchar(900) NULL,
 TradeNmE  varchar(254) NULL,
 InnNxCon  INT NULL,
 TradeNmNxCon  INT NULL,
 Id_DrugFmNmRCon  INT NULL,
 Id_FormNameCon  INT NULL,
 Org_SubCastId  INT NULL,
 Org_ProviderId  INT NULL,
 Enddate  datetime NULL,
 IsNotOnlyLS  bit NULL,
 PrUppdate  datetime NULL,
 PrInsertDate  datetime NULL,
 AVGPriceStart  decimal(18,2) NULL,
 PriceEnd  decimal(18,2) NULL,
 ChannelFinanceNm  varchar(100) NULL,
 StartDateExec  date NULL,
 EndDateExec  date NULL,
 ATCCode  varchar(7) NULL,
 ATCmNR  varchar(208) NULL,
 Org_SubCast_INN  varchar(20) NULL,
 Org_SubCastKPP  varchar(20) NULL,
 WinnerINN  varchar(20) NULL,
 LawNm   varchar(30) NULL,
 PlatformNm  varchar(100) NULL

);