ALTER DATABASE HWC_DATA_LANCET SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
go
ALTER DATABASE HWC_DATA_LANCET
SET ALLOW_SNAPSHOT_ISOLATION ON
go
ALTER DATABASE HWC_DATA_LANCET
SET READ_COMMITTED_SNAPSHOT ON
go
ALTER DATABASE HWC_DATA_LANCET SET MULTI_USER; 
go